resources:
# we are not going to create our own argocd cluster here. 
# We are going to use openshift-gitops one
#- argocd.yaml
- argocd-petclinic-project.yaml
- argocd-app-dev.yaml
- argocd-app-stage.yaml

patchesStrategicMerge:
- tmp-argocd-app-patch.yaml